create table employee
(
    id     bigint not null,
    name   varchar(255),
    status enum ('EVEN','ODD'),
    primary key (id)
);

/*search statement generated by hibernate*/
select emp.id, emp.name, emp.status
from employee emp
where emp.id = ?
  and (emp.status = 'EVEN');